blog:
  header: "fswq's blog"
  warning: '⚠️  ：图片默认大小 1200 * 600 px'
  info: '❤️  hello, 枫上雾棋, welcome back!'
  question: 
    title:
      type: 'input'
      name: 'title'
      default: 'JavaScript 居然能干这个'
      message: '文章标题'
    original:
      type: 'confirm'
      name: 'original'
      default: true
      message: '是否原创'
    tag:
      type: 'checkbox'
      name: 'tag'
      default: ['FrontEnd']
      message: '文章分类'
      choices: ['FrontEnd','NodeJS','Visualization']
      pageSize: 10
