name: Blog
on:
  push:
    branches:
      - dev

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn
      - run: yarn gatsby build --prefix-paths
        env:
          APP: blog
          META_AUTHOR: 枫上雾棋
          META_TITLE: 枫上雾棋的 blog
          META_DECS: 枫上雾棋的 blog
          SITE_URL: https://blog.fengshangwuqi.com
          PATH_PREFIX: /
          SOURCES: posts,zhoubao
          SIZE: 6
          TRACKING_ID: UA-114534441-1

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          publish_branch: master
          publish_dir: ./public

  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          tags: fswq/blog:latest,fswq/blog:1.0.0
