name: Blog
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn
      - run: yarn start bg b

      - uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.REPO_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
