name: Blog
on:
  push:
    branches:
      - dev
    paths:
      - "src-app/blog/**"
      - "posts/**"
      - "zhoubao/**"
  schedule:
    - cron: "0 4 * * SUN" # SUN-noon

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'docs(r)') || contains(github.event.schedule, '0 4 * * SUN')"
    steps:
      - run: sudo apt update
      - run: sudo apt -y upgrade
      - run: sudo apt install -y libpng-dev autoconf libpng-dev pkg-config nasm

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
      - run: pnpm install
      - run: pnpm appkit build blog

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
