name: Blog
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn
      - run: yarn gatsby build --prefix-paths
        env:
          APP: blog
          META_AUTHOR: 枫上雾棋
          META_TITLE: 枫上雾棋的 blog
          META_DECS: 枫上雾棋的 blog
          META_SOCIAL_TWITTER: "@fengshangwuqi"
          META_SOCIAL_GITHUB: FengShangWuQi
          META_CONTACT_EMAIL: fengshangwuqi@gmail.com
          SITE_URL: https://blog.fengshangwuqi.com
          PATH_PREFIX: /
          CMS_PATH: src-app/blog/cms/cms.js
          SOURCES: static/assets,posts,zhoubao
          SIZE: 6
          TRACKING_ID: ${{ secrets.TRACKING_ID }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          publish_branch: master
          publish_dir: ./public
