name: Blog
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn
      - run: yarn gatsby build --prefix-paths
        env:
          APP: blog
          SITE_URL: https://blog.fengshangwuqi.com
          PATH_PREFIX: /
          META_TITLE: 枫上雾棋的 storybook
          META_DECS: 枫上雾棋的 storybook
          SOURCES: static/assets,posts,zhoubao
          TRACKING_ID: ${{ secrets.TRACKING_ID }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          publish_branch: master
          publish_dir: ./public
