name: Blog
on:
  push:
    branches:
      - dev
    paths:
      - "src-app/blog/**"
      - "posts/**"
      - "zhoubao/**"
  schedule:
    - cron: "0 4 * * SUN" # SUN-noon

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'docs(r)') || contains(github.event.schedule, '0 4 * * SUN')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "14"

      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm appkit build blog

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
