name: Lighthouse
on:
  push:
    branches:
      - dev

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn
      - run: yarn gatsby build --prefix-paths
        env:
          APP: blog
          SITE_URL: https://blog.fengshangwuqi.com
          PATH_PREFIX: /
          META_TITLE: 枫上雾棋的 storybook
          META_DECS: 枫上雾棋的 storybook
          SOURCES: static/assets,posts,zhoubao
          SIZE: 6
          TRACKING_ID: ${{ secrets.TRACKING_ID }}

      - run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
