name: Packages
on:
  push:
    branches:
      - dev
    paths:
      - packages/**

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" > ~/.npmrc
      - run: yarn
      - run: yarn pkg:build
      - run: yarn pkg:r
