name: Post
on:
  push:
    branches:
      - post
    paths:
      - "posts/**"
      - "zhoubao/**"
  schedule:
    - cron: "0 4 * * SUN" # SUN-noon

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'docs(r)') || contains(github.event.schedule, '0 4 * * SUN')"
    steps:
      - uses: actions/checkout@v3
      - uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          source_ref: "post"
          target_branch: "dev"

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run r::create
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
