name: Storybook
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn
      - run: yarn gatsby build --prefix-paths
        env:
          APP: storybook
          SITE_URL: https://storybook.fengshangwuqi.com
          PATH_PREFIX: /
          META_TITLE: 枫上雾棋的 storybook
          META_DECS: 枫上雾棋的 storybook
          SOURCES: src-core,src-components,utils,cases
          SIZE: 6
          TRACKING_ID: ${{ secrets.TRACKING_ID }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_TOKEN }}
          external_repository: FengShangWuQi/storybook
          publish_dir: ./public
