name: Storybook
on:
  push:
    branches:
      - storybook

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: storybook

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_TOKEN }}
          external_repository: FengShangWuQi/storybook
          publish_dir: ./
