name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: install dependencies
      run: |
        npm ci
        cd tools
        npm install && npm run bootstrap
    - name: run tsc
      run: npm run tsc
    - name: run test
      run: npm test