name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup snyk
      uses: clarkio/snyk-cli-action@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: snyk test
      run: snyk test

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: install dependencies
      run: |
        npm ci
        cd tools/taskbook
        npm ci
    - name: run test
      run: npm test