name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt -y upgrade
      - run: sudo apt install -y libpng-dev autoconf libpng-dev pkg-config nasm

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
      - run: pnpm install
      - run: pnpm test

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
