name: Test
on:
  pull_request:
    branches:
      - dev
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'docs(r)') || contains(github.event.schedule, '0 0 * * 0')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: yarn install
      - run: yarn test

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
          fail_ci_if_error: true
